chore: update read me file for post funding
Health-Education-England/TIS-SYNC pull request #251
Opened 2024-07-03 12:02 UTC by jayanta2018

TIS21-5812

All the relevant confluence pages have been updated.

2024-07-03 14:55 UTC, JosephKelly requested changes

2024-07-03 15:00 UTC, jayanta2018 commented on README.md
> +| **PostFundingStatusSyncJob**             |      PostFundingStatusSyncJob       |         postFundingStatusSyncJob       |                                              Re-run **Post Funding Status S
I beg your pardon, Pepe, what is SVG?

2024-07-03 15:51 UTC, JosephKelly commented on README.md
> +| **PostFundingStatusSyncJob**             |      PostFundingStatusSyncJob       |         postFundingStatusSyncJob       |                                              Re-run **Post Funding Status S
https://github.com/Health-Education-England/TIS-SYNC/blob/main/jobDependency.svg

2024-07-03 15:51 UTC, JosephKelly commented on README.md
> +| **PostFundingStatusSyncJob**             |      PostFundingStatusSyncJob       |         postFundingStatusSyncJob       |                                              Re-run **Post Funding Status S
See: https://github.com/Health-Education-England/TIS-SYNC/blob/e7842301b3a3c3a12e869e7e657662804905502b/README.md?plain=1#L16

2024-07-04 10:44 UTC, jayanta2018 commented on README.md
> +| **PostFundingStatusSyncJob**             |      PostFundingStatusSyncJob       |         postFundingStatusSyncJob       |                                              Re-run **Post Funding Status S
Added and updated now

2024-07-04 11:34 UTC, JosephKelly approved these changes

2024-07-04 11:34 UTC, merged