feat: DBC and HeeUser requests from TSS
Health-Education-England/TIS-SYNC pull request #252
Opened 2024-07-10 13:17 UTC by ReubenRobertsHEE

TIS21-6272

2024-07-12 10:14 UTC, JosephKelly requested changes
One import to change.
I'm happy enough with the rest if you want to leave them... if you're up for addressing the code smell too, that would be appreciated!

2024-07-12 15:21 UTC, ReubenRobertsHEE commented on src/test/java/uk/nhs/tis/sync/mapper/HeeUserMapperTest.java
> +import org.junit.Test;
Is this a more general upgrade for the project? I can't see any other tests that use JUnit5.

2024-07-12 15:27 UTC, JosephKelly commented on src/test/java/uk/nhs/tis/sync/mapper/HeeUserMapperTest.java
> +import org.junit.Test;
This test uses JUnit5 Jupiter annotations :smile: , i.e. `@ParameterizedTest` was introduced with JUnit5.

2024-07-12 15:44 UTC, ReubenRobertsHEE commented on src/test/java/uk/nhs/tis/sync/mapper/HeeUserMapperTest.java
> +import org.junit.Test;
Sorry, I was being obtuse. Fixed now

2024-07-12 15:48 UTC, JosephKelly submitted a review, later dismissed

2024-07-12 15:48 UTC, JosephKelly commented on src/main/java/uk/nhs/tis/sync/dto/DmsDtoType.java
> +  private static class Schemas {
Noice!

2024-07-12 15:49 UTC, JosephKelly approved these changes
:joy:

2024-07-12 15:49 UTC, ReubenRobertsHEE commented on src/main/java/uk/nhs/tis/sync/dto/DmsDtoType.java
> +  private static class Schemas {
Sorry, one last code smell straggler came through after your approval 🐑

2024-07-12 15:49 UTC, merged

2024-07-15 08:29 UTC, ReubenRobertsHEE commented
Testing on staging shows there is a permission issue for the HeeUser requests from the Profile service. I'm looking into this now.

e.g.:

```
2024-07-15 08:11:40.048 ERROR 1 --- [   Thread-12274] u.n.tis.sync.service.DataRequestService  : 403 Forbidden: [Access is denied]
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [Access is denied]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:612) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at com.transformuk.hee.tis.profile.client.service.impl.ProfileServiceImpl.getSingleAdminUser(ProfileServiceImpl.java:188) ~[profile-client-2.8.1.jar:na]
```